SELECT C.DATE, C.PRIMARY_TYPE, C.DESCRIPTION, C.LOCATION_DESCRIPTION, C.ARREST, C.YEAR,
P.NAME_OF_SCHOOL, P.ELEMENTARY_MIDDLE_OR_HIGH_SCHOOL, P._STATE, P.COMMUNITY_AREA_NAME
FROM CRIME C
INNER JOIN PUBLIC_SCHOOLS P 
ON C.COMMUNITY_AREA_NUMBER = P.COMMUNITY_AREA_NUMBER;

SELECT  C.COMMUNITY_AREA_NAME, S.STREET_ADDRESS, S.CITY, S._STATE, S.ZIP_CODE
FROM CENSUS_TABLE C
JOIN PUBLIC_SCHOOLS S
ON C.COMMUNITY_AREA_NUMBER = S.COMMUNITY_AREA_NUMBER;

SELECT SCHOOL_ID, NAME_OF_SCHOOL, AVERAGE_STUDENT_ATTENDANCE, ARREST
FROM PUBLIC_SCHOOLS
JOIN CRIME USING(COMMUNITY_AREA_NUMBER)
GROUP BY SCHOOL_ID, NAME_OF_SCHOOL, ARREST;

SELECT P.SCHOOL_ID, P.NAME_OF_SCHOOL, P._STATE, C.DESCRIPTION, C.LOCATION_DESCRIPTION, C.ARREST
FROM CRIME C
JOIN PUBLIC_SCHOOLS P 
ON C.WARD = P.WARD
WHERE C.ARREST = 'TRUE'
GROUP BY P.NAME_OF_SCHOOL, P.SCHOOL_ID, C.DESCRIPTION, C.LOCATION_DESCRIPTION, C.ARREST;

SELECT D.COMMUNITY_AREA_NAME, D.PERCENT_AGED_16__UNEMPLOYED, D.PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA, C.PRIMARY_TYPE, C.DESCRIPTION, C.LOCATION_DESCRIPTION
FROM CENSUS_TABLE D
INNER JOIN CRIME C
ON D.COMMUNITY_AREA_NUMBER = C.COMMUNITY_AREA_NUMBER
ORDER BY D.PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA;

SELECT COMMUNITY_AREA_NAME, MAX(PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA) AS "% AGE 25 WITHOUT HS DIPLOMA"
FROM CENSUS_TABLE
GROUP BY COMMUNITY_AREA_NAME
ORDER BY "% AGE 25 WITHOUT HS DIPLOMA" DESC;

SELECT D.COMMUNITY_AREA_NAME, D.PERCENT_OF_HOUSING_CROWDED, D.PERCENT_HOUSEHOLDS_BELOW_POVERTY, C.YEAR, COUNT(ARREST) AS "NUMBER OF ARRESTS"
FROM CENSUS_TABLE D
JOIN CRIME C
ON D.COMMUNITY_AREA_NUMBER = C.COMMUNITY_AREA_NUMBER
GROUP BY D.COMMUNITY_AREA_NAME, D.PERCENT_OF_HOUSING_CROWDED, D.PERCENT_HOUSEHOLDS_BELOW_POVERTY, C.YEAR, C.ARREST; 



