UPDATE EMPLOYEES SET EMAIL='NOT AVAILABLE';

INSERT INTO COUNTRIES VALUES('US', 'UNITED STATE', 2);
INSERT INTO JOB_GRADE (GRADE_LEVEL, LOWEST_SAL) VALUES('D', 2100);

SELECT COUNT(DISTINCT JOB_ID)
FROM EMPLOYEES;

SELECT SUM(SALARY)
FROM EMPLOYEES;

SELECT MIN(SALARY)
FROM EMPLOYEES;

SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT AVG(SALARY), COUNT(*)
FROM EMPLOYEES
WHERE DEPARTMENT_ID=90;

SELECT MAX(SALARY) AS "HIGHEST SALARY",
		MIN(SALARY) AS "LOWEST SALARY",
		SUM(SALARY) AS "TOTAL SALARIES",
		AVG(SALARY) AS "AVERAGE SALARY"
FROM EMPLOYEES; 

SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT MAX(SALARY)-MIN(SALARY) AS "SALARY DIFFERENCE"
FROM EMPLOYEES;

SELECT MANAGER_ID, MIN(SALARY)
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
ORDER BY MIN(SALARY) DESC;

SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT JOB_ID, AVG(SALARY)
FROM EMPLOYEES
WHERE JOB_ID<>'IT_PROG'
GROUP BY JOB_ID;

SELECT SUM(SALARY) AS "TOTAL SALARY", MAX(SALARY) AS "MAX SALARY", MIN(SALARY) AS "MIN SALARY", AVG(SALARY) AS "AVERAGE SALARY"
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

SELECT JOB_ID, MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY >= 4000
GROUP BY JOB_ID;

SELECT JOB_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING MAX(SALARY) >= 4000;

SELECT JOB_ID, DEPARTMENT_ID, AVG(SALARY) AS "AVERAGE SALARY", COUNT(*) AS "NO. OF EMPLOYEES"
FROM EMPLOYEES 
GROUP BY JOB_ID, DEPARTMENT_ID
HAVING COUNT(*)>10;

SELECT DISTINCT JOB_ID, EMPLOYEE_ID
FROM EMPLOYEES;

SELECT JOB_ID, ARRAY_AGG(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY JOB_ID;

UPDATE EMPLOYEES 
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '124', '999')
WHERE PHONE_NUMBER LIKE '%124%';

SELECT *
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) >=8;

UPDATE EMPLOYEES
SET EMAIL = CONCAT(EMAIL, '@EXAMPLE.COM');

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME = UPPER(FIRST_NAME); 

SELECT  RIGHT(PHONE_NUMBER, 4) AS "PH.NO." 
FROM EMPLOYEES; 

SELECT JOB_TITLE,
SUBSTR(JOB_TITLE, 1, POSITION('' IN JOB_TITLE))
FROM JOBS;



